### ISSUE TITLE
GStreamer minimal required version must be increased up to `1.22`

### ISSUE THREAD

**Issue by inobelar** [ReFormationPro/Gstreamer-H264-Encryption#3]
Hi! After trying to build library on `Ubuntu 22.04.4 LTS` with `GStreamer 1.20.3` , i spotted the next compilation error:

```c++
Gstreamer-H264-Encryption/gst-h264-encryption/src/h264_decrypt.c: In function ‘gst_h264_decrypt_before_nalu_copy’:
Gstreamer-H264-Encryption/gst-h264-encryption/src/h264_decrypt.c:159:31: error: ‘GST_H264_SEI_USER_DATA_UNREGISTERED’ undeclared (first use in this function)
  159 |       if (msg->payloadType == GST_H264_SEI_USER_DATA_UNREGISTERED) {
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Its occured, since [GstH264Parser :: GstH264SEIPayloadType::GST_H264_SEI_USER_DATA_UNREGISTERED](https://gstreamer.freedesktop.org/documentation/gst-plugins-bad-codecparsers/gsth264parser.html?gi-language=c#GstH264SEIPayloadType) was added since `Gstreamer 1.22`.

So, we need to increase minimal required GStreamer version in [meson.build](https://github.com/ReFormationPro/Gstreamer-H264-Encryption/blob/c16f526072732c12f6e6de74ad35cce7a85ffce9/meson.build#L11-L19) (currently there minimal version is `1.19`)

**Comment by oguzhanoztaskin** [comment]
Hi there,

Thank you for your interest in this project.

I tested on 1.22 and saw that writing H264 SEI is not supported yet. According to [here](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/d07ffae3433e955156f7572781c92b0067b8417b), it is added on 1.23.1 as in the screenshot:
![image](https://github.com/user-attachments/assets/e174ddd6-4141-4e94-bf57-63275b2c8f27)

Hence, I updated the minimum required version to 1.23.1 while merging your pull requests.

Best regards,
